version: "3.9"
services:
  postgres:
    image: postgres:13
    restart: always
    hostname: postgres
    ports:
      - 5432:5432
    env_file:
      - .development.env
    command: [ "postgres", "-c", "log_statement=all" ]
  redis:
    image: library/redis:6.2.4-alpine
    restart: always
    hostname: redis
    ports:
      - 6379:6379
